name: ezoom_todolist
description: "Just one test project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^5.0.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  google_fonts: ^6.0.0
  flutter_secure_storage:
  rxdart:
  design_system:
    path: ./packages/design_system

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: "^0.13.1"
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "./assets/icon/ezoom_logo.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#000000"
