name: ezoom_todolist
description: "Just one test project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^5.0.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  overlay_support: ^2.1.0
  flutter_secure_storage:
  diacritic: ^0.1.4
  rxdart:
  design_system:
    path: ./packages/design_system

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
